SELECT EXTRACT (DAY FROM SYSDATE) AS DIA, EXTRACT (MONTH FROM SYSDATE) AS MES, EXTRACT (YEAR FROM SYSDATE) AS AÑO FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,12) AS "Fecha Actual" FROM DUAL;
SELECT CEIL(MONTHS_BETWEEN(SYSDATE,DATE'2022-02-25')) AS "MESES ENTRE HOY Y 2022-02-25" FROM DUAL;