CREATE TABLE MINORISTA (
    CIF varchar2(9) CHECK (LENGTH(CIF) = 9) PRIMARY KEY,
    NOM varchar2(50) NOT NULL
);
CREATE TABLE PRODUCTE (
    NOM varchar2(50) PRIMARY KEY,
    PREU_UNITARI NUMBER(7,2) NOT NULL
);
CREATE TABLE REPARTIDOR (
    NUM_SS varchar2(13) PRIMARY KEY,
    NOM varchar2(50) NOT NULL
);
CREATE TABLE COMANDA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    PREU_TOTAL NUMBER(7,2) NOT NULL,
    FECHA DATE NOT NULL,
    CIF_MINORISTA varchar2(9) NOT NULL,
    NOM_PRODUCTE varchar2(50),
    QUANTITAT NUMBER NOT NULL,
    FOREIGN KEY (CIF_MINORISTA) REFERENCES MINORISTA (CIF),
    FOREIGN KEY (NOM_PRODUCTE) REFERENCES PRODUCTE (NOM)
);
CREATE TABLE INTENT_ENTREGA (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    FECHA DATE NOT NULL,
    ESTAT varchar2(20) NOT NULL,
    CODI_REPROGRAMAT NUMBER,
    CODI_COMANDA NUMBER,
    NUM_SS_REPARTIDOR varchar2(13),
    UNIQUE(CODI_COMANDA,FECHA),
    FOREIGN KEY (CODI_REPROGRAMAT) REFERENCES INTENT_ENTREGA (CODI),
    FOREIGN KEY (CODI_COMANDA) REFERENCES COMANDA (CODI),
    FOREIGN KEY (NUM_SS_REPARTIDOR) REFERENCES REPARTIDOR (NUM_SS)
);

