SELECT MONTHS_BETWEEN(DATA_FI, DATA_INICI)/12 AS "CANTIDAD DE MESES EN LA PLAZA",NSS_EMPLEAT,CODI_PLACA FROM OCUPA;
SELECT CODI_PLACA_SUPERVISORA, AVG(SALARI) FROM PLACA WHERE CODI_PLACA_SUPERVISORA IS NOT NULL GROUP BY CODI_PLACA_SUPERVISORA;
SELECT NOM,SALARI FROM PLACA WHERE CODI_PLACA_SUPERVISORA IS NULL;
SELECT AVG(MONTHS_BETWEEN(DATA_FI,DATA_INICI)) FROM OCUPA;
SELECT NOM_TIPUS_PLACA,MAX(SALARI),MIN(SALARI) FROM PLACA GROUP BY NOM_TIPUS_PLACA;
SELECT NOM_TIPUS_PLACA,MAX(SALARI),MIN(SALARI) FROM PLACA GROUP BY NOM_TIPUS_PLACA HAVING AVG(SALARI) >= 3000;
SELECT COUNT(*) FROM PLACA GROUP BY NOM_TIPUS_PLACA ORDER BY AVG(SALARI) DESC FETCH FIRST ROW ONLY;