CREATE TABLE CLIENT (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    ADREÇA VARCHAR2(50) NOT NULL,
    CODI_POSTAL VARCHAR2(5) NOT NULL,
    TELEFON NUMBER(12),
    EMAIL VARCHAR2(50)
);
CREATE TABLE MODEL (
    ID NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    ANY_LLANÇAMENT NUMBER(4) NOT NULL,
    NOM VARCHAR2(50) NOT NULL,
    MARCA VARCHAR2(20) NOT NULL,
    ID_SUBSTITUEIX NUMBER,
    FOREIGN KEY (ID_SUBSTITUEIX) REFERENCES MODEL (ID),
    UNIQUE(ANY_LLANÇAMENT,NOM,MARCA)
);
CREATE TABLE PROVA (
    ID_MODEL NUMBER,
    DNI_CLIENT VARCHAR2(9),
    FECHA_PROVA DATE NOT NULL,
    PRIMARY KEY (ID_MODEL,DNI_CLIENT),
    FOREIGN KEY (ID_MODEL) REFERENCES MODEL (ID),
    FOREIGN KEY (DNI_CLIENT) REFERENCES CLIENT (DNI)
);
CREATE TABLE COTXE (
    MATRICULA VARCHAR2(7) PRIMARY KEY,
    PREU NUMBER(9,2) NOT NULL,
    COLOR VARCHAR2(20) NOT NULL,
    ID_MODEL NUMBER NOT NULL,
    DNI_CLIENT VARCHAR2(9),
    FOREIGN KEY (ID_MODEL) REFERENCES MODEL (ID),
    FOREIGN KEY (DNI_CLIENT) REFERENCES CLIENT (DNI)
);
CREATE TABLE REVISIO (
    CODI NUMBER GENERATED AS IDENTITY PRIMARY KEY,
    DESCRIPCIO VARCHAR2(500) CHECK (LENGTH (DESCRIPCIO) > 100) NOT NULL,
    FECHA_REVISIO DATE NOT NULL,
    MATRICULA_COTXE VARCHAR2(7) NOT NULL,
    FOREIGN KEY (MATRICULA_COTXE) REFERENCES COTXE (MATRICULA)
);

INSERT INTO client VALUES('46788014k','Alex','Calle 7',17016,34687631089,'asanchez@gmail.com');
INSERT INTO model (any_llançament,nom,marca) VALUES(2018,'Picasso','Citroen');
INSERT INTO model (any_llançament,nom,marca,id_substitueix) VALUES(2020,'Supra GTR','Toyota',1);
INSERT INTO prova VALUES(2,'46788014k',DATE'2024-12-12');
INSERT INTO cotxe VALUES('4519ABC',50000.00,'Vermell',2,'46788014k');
INSERT INTO revisio (descripcio,fecha_revisio,matricula_cotxe) VALUES ('Toyota Supra GTR de color rojoToyota Supra GTR de color rojoToyota Supra GTR de color rojoToyota Supra GTR de color rojo',DATE'2025-01-22','4519ABC');

ALTER TABLE client DROP COLUMN telefon;
UPDATE client SET nom = 'Hugo' WHERE nom = 'Alex';
ALTER TABLE prova ADD Observacions varchar2(2000);
DELETE FROM prova WHERE fecha_prova < DATE'2025-01-01';
